config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "/start" => 'steps#step1', as: :step1
  post "/start" => 'passwords#verify', defaults: {step: 1}

  get "/congratulations" => 'steps#step2', as: :step2
  post "/congratulations" => 'passwords#verify', defaults: {step: 2}  

  get "/cryptography" => 'steps#step3', as: :step3
  post "/cryptography" => 'steps#step3', defaults: {step: 3}

  get "/step4" => 'steps#step4', as: :step4
  post "/step4" => 'passwords#verify', defaults: {step: 4}

  get "/step5" => 'steps#fake_step5', as: :fake_step5

  get "/step_delta" => 'steps#step5', as: :step5
  post "/step_delta" => 'passwords#verify', defaults: {step: 5}

  get "/step_52" => 'steps#step6', as: :step6
  post "/step_52" => 'steps#step6'

  get "/there-will-be-cake" => 'steps#step7', as: :step7
  post "/there-will-be-cake" => 'steps#step7'

  get "/there-is-no-cake" => 'steps#step8', as: :step8
  post "/there-is-no-cake" => 'passwords#verify', defaults: {step: 8}

  get "/secure-step" => 'steps#step9', as: :step9
  post "/secure-step" => "passwords#verify", defaults: {step: 9}

  get "/here-is-your-cake" => 'steps#finish', as: :finish

  get "/ok-ik-wil-een-job" => 'candidatures#new', as: :new_candidature
  post "/ok-ik-wil-een-job" => 'candidatures#create', as: :candidatures

  get "/sollicitatie-ontvangen" => 'candidatures#received', as: :received_candidatures

  get "/404" => 'errors#error_404'
  get "/500" => 'errors#error_500'

  root to: redirect('/start')
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/candidature.rb
class Candidature < ActiveRecord::Base
  validates_presence_of :name, :motivation, :email, :phone_number
  serialize :steps

  mount_uploader :resume, ResumeUploader
end

app/models/step.rb
class Step
  include Rails.application.routes.url_helpers

  Steps = [
    {
      password: 'WeGaanGemakkelijkVanStart',
      url:      -> { step1_path }
    },
    {
      password: 'HetWordtWatMoeilijker',
      exit_code: 'stap1',
      url:      -> { step2_path }
    },
    {
      password: 'mabl bl khm19 xgvkrimbhg pahh',
      exit_code: 'stap2',
      url:      -> { step3_path }
    },
    {
      password: 'IkSnapHoeHeadersWerken',
      exit_code: 'stap-twee',
      url:      -> { step4_path }
    },
    {
      password: 'Oei, En Nu?',
      exit_code: 'nummer-drie',
      url:      -> { step5_path }
    },
    {
      password: 'SQL Injecting like a Boss',
      exit_code: 'step-delta-survivor',
      url:      -> { step6_path }
    },
    {
      password: 'X-I-Am-A-Teapot',
      exit_code: 'sql-injector',
      url:      -> { step7_path }
    },
    {
      password: 'WebSocketsAreCool',
      exit_code: 'api-king',
      url:      -> { step8_path }
    },
    {
      password: -> (password) { password.split().join =~ %r{2Tk0Erl5riWB5B2IEJpBssGDYRBRDDdB/QjRcNyaaMyq5F4h7QMXff0Iun9AH8i5} },
      exit_code: 'websocket-master',
      url:      -> { step9_url(protocol: 'https', host: 'hackature.nl') }
    },
    {
      exit_code: 'pr0-h4x0r',
      url:      -> { finish_path }
    }
  ]

  class << self
    def for(step)
      idx = step.to_i - 1
      new(Steps[idx], step.to_i)
    end

    def finish
      new(Steps.last, Steps.count)
    end
  end

  attr_accessor :idx

  def initialize(attrs, idx)
    @attrs = attrs
    @idx = idx
  end

  def first?
    @idx == 1
  end

  def last?
    @idx == Steps.size
  end

  def next
    self.class.for(@idx + 1)
  end

  def url
    proc = @attrs[:url]
    self.instance_exec &proc
  end

  def password
    @attrs[:password]
  end

  def exit_code
    @attrs[:exit_code]
  end

  def verify(password)
    if self.password.respond_to?(:call)
      self.password.call(password)
    else
      password == self.password
    end
  end
end

## ROT 19 Encryption Algo
class String
  def rot(num = 19)
    return self.split("").collect { |ch|
      if /^[a-z]$/ === ch
        ((ch.ord + num - 'a'.ord) % 26 + 'a'.ord).chr
      elsif /^[A-Z]$/ === ch
        ((ch.ord + num - 'A'.ord) % 26 + 'A'.ord).chr
      else
        ch
      end
    }.join("")
  end
  alias rot19 rot
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidatures_controller.rb
class CandidaturesController < ApplicationController
  respond_to :html

  def new
    @candidature = Candidature.new
  end

  def create
    @candidature = Candidature.new(candidature_params)
    @candidature.steps = cookies.encrypted[:steps]
    @candidature.save

    respond_with(@candidature, location: received_candidatures_path)
  end

  def received
  end

  private
  def candidature_params
    params.require(:candidature).permit(:name, :email, :phone_number, :resume, :motivation)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def error_404
  end

  def error_500
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  def verify
    if current_step.verify(password_param)
      redirect_to current_step.next.url
    else
      redirect_to current_step.url, failed: true
    end
  end

  private
  def current_step
    @step ||= Step.for(params[:step])
  end

  def password_param
    params[:p4ssw0rd] ||
    params[:password] ||
    params[:passw0rd]
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_filter :set_current_step
  # Disabled because it's possible to solve this problems in different browsers
  # before_filter :ensure_step_order
  after_filter :save_current_step

  def step1
    session[:encrypt] = 0
    @password = @step.password
  end

  def step2
    @password = @step.password
  end

  def step3
    @password = @step.password
    if params[:passw0rd] && @step.verify(params[:passw0rd].rot19)
      redirect_to @step.next.url
    else 
      @encryption_chances = encryption_chances if params[:passw0rd]
    end
  end

  def step4
    @password = @step.password
    headers['X-S3cr3t-P4ssw0rd'] = @password
  end

  def step5
    @password = @step.password
  end

  def step6
    if @step.verify(params[:passw0rd])
      redirect_to @step.next.url
    end

    @password = @step.password
    headers['X-Hint'] = "http://xkcd.com/327"
  end

  def step7
    @password = @step.password

    if @step.verify(request.headers['X-Password'])
      redirect_to @step.next.url
    elsif params[:passw0rd] == @password
      flash[:error] = "Expected X-Password header to equal password"
    end
  end

  def step8
  end

  def step9
  end

  def finish
  end
  
  private
  def ensure_step_order
    unless @step.first?
      visited_steps = cookies.encrypted[:steps]

      if !visited_steps || visited_steps.blank? # No cookie? Go to step 1
        redirect_to(Step.for(1).url)
      elsif visited_steps.last < @step.idx - 1
        redirect_to(Step.for(visited_steps.last).url)
      end
    end
  end

  def save_current_step
    return if @stop

    steps = cookies.encrypted[:steps] || []
    steps << @step.idx
    cookies.encrypted[:steps] = steps
  end

  def set_current_step
    step_idx = params[:action].to_s[/step(\d+)/, 1]
    @step = step_idx ? Step.for(step_idx) : Step.finish
  end

  def encryption_chances   
    session[:encrypt] = session[:encrypt].present? ? (session[:encrypt] + 1) : 1
    session[:encrypt] == 5 ? (redirect_to step1_path) : session[:encrypt]
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidatures/new.html.erb
<h1><%= t('.title') %></h1>

<p><%= t('.explanation_html') %></p>

<div id="candidature">
  <%= simple_form_for @candidature do |f| %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :phone_number %>
    <%= f.input :motivation, input_html: {rows: 16} %>
    <%= f.input :resume %>

    <%= f.button :submit %>
  <% end %>
</div>

app/views/candidatures/received.html.erb
<h1><%= t('.title') %></h1>

<p><%= t('.explanation_html') %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackature</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <%= yield :head %>
</head>
<body>

<div id="content">
  <%= yield %>

  <% unless !@step || @step.first? || @step.last? %>
    <footer id="no-shame">
      <%= t('.give_up_html', link: new_candidature_path) %>
    </footer>
  <% end %>
</div>

</body>
</html>

<%= yield :end %>

app/views/steps/fake_step4.html.erb
<% content_for(:head) do %>
  <meta http-equiv="refresh" content="5; url=/start">
<% end %>
<h1><%= t('.title') %></h1>

<p><%= t('.explanation_html') %></p>

app/views/steps/finish.html.erb
<h1><%= t('.title') %></h1>

<p><%= t('.explanation_html', link: new_candidature_path) %></p>

app/views/steps/step1.html.erb
<% content_for(:head) do %>
  <script>
    $(document).on('click', '#p4ssw0rd', function() {
      alert('OK, we geven het toe, het is niet ZO gemakkelijk...');
      return false;
    })
  </script>
<% end %>

<h1><%= t('.title') %></h1>

<p><%= t('.explanation_html', password: @password) %></p>

<%= form_tag do %>
  <%= password_field_tag("p4ssw0rd", "of is dit het?", readonly: true, id: 'p4ssw0rd') %>

  <%= submit_tag t('.hack') %>
<% end %>

app/views/steps/step2.html.erb
<h1><%= t('.title') %></h1>

<p><%= t('.explanation_html') %></p>

<%= form_tag do %>
  <%= password_field_tag("passw0rd", "", id: 'p4ssw0rd') %>

  <%= submit_tag t('.hack'), disabled: true, id: 'submit' %>
<% end %>

<% content_for(:end) do %>
<%= (" " * 600 + "\n") * 20 %>
<!-- WTF!! Wat is dit lang... -->
<%= (" " * 600 + "\n") * 20 %>
<!-- EINDE! -->
<%= (" " * 600 + "\n") * 20 %>
<!-- This is not the scrolling you are looking for -->
<%= (" " * 600 + "\n") * 20 %>
<script>
  (function(q, _, m, u, s, i, c, $) {
    u = arguments.length * u
    s = '#'
    c = 'submit'
    $ = ['ThisIsThePassword', 'DitIsHetWachtwoord', 'OfIsHetDit', 'HetBlijftEenvoudig', 'HetWordAlWatMoeilijker', 'SecurityByObscurity', 'OKHetKomtGoed', 'JeBentEenEchteHacker', 'GoedGedaan', 'Volgende', '<%= @password %>', 'AlleGekheidOpEenStokje', 'WeGaanGemakkelijkVanStart', 'Moop3ahXahghuc7aemai7piucheXah2m', 'DitIsGeheim']
    var password = s + 'p4ssw0r' + (("" + i)[u++])
    m != undefined ? i = function (i) { return $[i] } : function () { "RealPassword" }

    q.i = function () { m(s+c).attr('disabled', false) }
    q._ = function () { if (m(this).val() == i(++u)) q.i(); else window.location = "/start" }
    m(_).on('change', password, q._)
  })(window, document, $, 2)
</script>
<% end %>

app/views/steps/step3.html.erb
<h1><%= t('.title') %></h1>

<p><%= t('.explanation_html') %></p>

<%= form_tag do %>
  <%= password_field_tag("passw0rd", "", id: 'p4ssw0rd') %>

  <%= submit_tag t('.hack'), id: 'submit' %>
    <pre><%= "#{5-@encryption_chances} chances Left" if @encryption_chances.present? && (@encryption_chances > 0)  %></pre>
<% end %>

app/views/steps/step4.html.erb
<h1><%= t('.title') %></h1>

<p><%= t('.explanation_html') %></p>

<%= form_tag do %>
  <%= password_field_tag("passw0rd", "", id: 'p4ssw0rd') %>

  <%= submit_tag t('.hack'), id: 'submit' %>
<% end %>

app/views/steps/step5.html.erb
<script>
  $(document).on('submit', 'form', function () { return false; })
</script>

<h1><%= t('.title') %></h1>

<p><%= t('.explanation_html') %></p>

<%= form_tag do %>
  <%= password_field_tag("passw0rd", @password, id: 'p4ssw0rd') %>
<% end %>

app/views/steps/step6.html.erb
<h1><%= t('.title') %></h1>

<p><%= t('.explanation_html') %></p>

<%= form_tag do %>
  <%= password_field_tag("passw0rd", '', id: 'p4ssw0rd') %>
  <%= submit_tag t('.hack') %>
<% end %>

<% case params[:passw0rd] %>
<% when /['"].*SELECT.*;--/i %>
  <pre>
  | steps | passwords        |
  | 42    | <%= @password %> |
  </pre>
<% when /['"]/ %>
  <pre>ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM steps' at line 1</pre>
<% end %>

app/views/steps/step7.html.erb
<h1><%= t('.title') %></h1>

<p><%= t('.explanation_html', password: @password) %></p>

<%= form_tag do %>
  <%= password_field_tag("passw0rd", '', id: 'p4ssw0rd') %>
  <%= submit_tag t('.hack') %>
<% end %>

<pre><%= flash[:error] %></pre>

app/views/steps/step8.html.erb
<% content_for :head do %>
  <script type="text/javascript" src="//socket.q-music.nl/js/q+sock.js"></script>
<% end %>

<h1><%= t('.title') %></h1>

<p><%= t('.explanation_html', password: @password) %></p>

<%= form_tag do %>
  <%= password_field_tag("passw0rd", '', id: 'p4ssw0rd') %>
  <%= submit_tag t('.hack') %>
<% end %>

app/views/steps/step9.html.erb
<h1><%= t('.title') %></h1>

<p><%= t('.explanation_html') %></p>

<%= form_tag do %>
  <%= text_area_tag("passw0rd", '', id: 'p4ssw0rd', rows: 12, cols: 40) %>
  <%= submit_tag t('.hack') %>
<% end %>